language: node_js
node_js:
  - 13

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as test
before_script:
  - echo "no tests"

script:
  # Build
  - npm install serverless -g
  - npm install
  - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo OK